project_id: e1de9d3ed8fa1947485496f968632045
remote:
    host: https://richo542.atlassian.net
    type: jira
    project: SCRUM
bindings:
    - SCRUM-1
transitions:
    Story:
        start:
            transition_key: "21"
            display_name: In Arbeit
        done:
            transition_key: "41"
            display_name: Fertig
    Task:
        start:
            transition_key: "21"
            display_name: In Arbeit
        done:
            transition_key: "41"
            display_name: Fertig
