remote:
    host: https://tfs.intra.infineon.com/tfs
    type: azure
    project: MDI PCA AAI
bindings:
    - "400189"
transitions:
    Feature:
        start:
            transition_key: Active
            display_name: Active
        done:
            transition_key: Closed
            display_name: Closed
